server:
  port: 8081

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
      database: nosql
      uri: mongodb+srv://franksalazar:ZPyOdaFVHyETu9hH@cluster0.8unnc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
